var jsPaths_2 = { // add to all paths_*.js those lines: "groupPathsJSonName": "jsPaths_*" and "groupPathsName": "paths_*"
  "ns0:svg": {
    "groupPathsJSonName": "jsPaths_2",
    "groupPathsName": "paths_2",
    "-xmlns:ns0": "http://www.w3.org/2000/svg",
    "-enable-background": "new 0 0 612 792",
    "-height": "792px",
    "-id": "Layer_1",
    "-version": "1.1",
    "-viewBox": "0 0 612 792",
    "-width": "612px",
    "-x": "0px",
    "-y": "0px",
    "-xml:space": "preserve",
    "ns0:g": {
      "-id": "Layer_3_1_",
      "ns0:g": {
        "-id": "Layer_2",
        "ns0:line": [
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.2",
            "-x2": "221.2",
            "-y1": "700",
            "-y2": "725.9"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "221.2",
            "-x2": "186.4",
            "-y1": "700",
            "-y2": "700"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.4",
            "-x2": "186.4",
            "-y1": "700",
            "-y2": "659.9"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.4",
            "-x2": "87.6",
            "-y1": "659.9",
            "-y2": "659.9"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "87.6",
            "-y1": "659.9",
            "-y2": "680.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "19.8",
            "-y1": "680.5",
            "-y2": "680.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "87.6",
            "-y1": "659.9",
            "-y2": "640"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "19.8",
            "-y1": "640",
            "-y2": "640"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "87.6",
            "-y1": "640",
            "-y2": "589.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "68",
            "-y1": "589.5",
            "-y2": "589.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "87.6",
            "-x2": "122",
            "-y1": "589.5",
            "-y2": "589.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "186.4",
            "-x2": "238",
            "-y1": "659.9",
            "-y2": "659.9"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "238",
            "-x2": "238",
            "-y1": "659.9",
            "-y2": "606"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "238",
            "-x2": "444",
            "-y1": "606",
            "-y2": "606"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "238",
            "-x2": "238",
            "-y1": "606",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "238",
            "-x2": "93.5",
            "-y1": "539",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.5",
            "-x2": "93.5",
            "-y1": "539",
            "-y2": "436.6"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.5",
            "-x2": "19.8",
            "-y1": "436.6",
            "-y2": "436.6"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.5",
            "-x2": "93.5",
            "-y1": "436.6",
            "-y2": "377.8"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "93.5",
            "-x2": "132.7",
            "-y1": "377.8",
            "-y2": "377.8"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "132.7",
            "-x2": "132.7",
            "-y1": "377.8",
            "-y2": "323.4"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.8",
            "-x2": "177.8",
            "-y1": "539",
            "-y2": "250.3"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "238",
            "-x2": "275",
            "-y1": "539",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "275",
            "-y1": "539",
            "-y2": "495"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "219",
            "-y1": "495",
            "-y2": "495"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "219",
            "-x2": "219",
            "-y1": "495",
            "-y2": "400"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "258",
            "-x2": "258",
            "-y1": "495",
            "-y2": "400"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "275",
            "-y1": "495",
            "-y2": "323.4"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "219",
            "-y1": "323.4",
            "-y2": "323.4"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "275",
            "-y1": "323.4",
            "-y2": "250"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "219",
            "-y1": "250",
            "-y2": "250"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "275",
            "-x2": "320.6",
            "-y1": "539",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.6",
            "-x2": "320.6",
            "-y1": "539",
            "-y2": "545"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320.6",
            "-x2": "374",
            "-y1": "539",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "374",
            "-y1": "539",
            "-y2": "565"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "374",
            "-y1": "539",
            "-y2": "490"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "335",
            "-y1": "490",
            "-y2": "490"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "335",
            "-x2": "335",
            "-y1": "490",
            "-y2": "539"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "374",
            "-y1": "490",
            "-y2": "410"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "330.2",
            "-y1": "410",
            "-y2": "410"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "374",
            "-y1": "410",
            "-y2": "308.3"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "374",
            "-x2": "320",
            "-y1": "308.3",
            "-y2": "308.3"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320",
            "-x2": "320",
            "-y1": "308.3",
            "-y2": "250"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320",
            "-x2": "393.3",
            "-y1": "250",
            "-y2": "250"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320",
            "-x2": "320",
            "-y1": "250",
            "-y2": "213"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "320",
            "-x2": "393.3",
            "-y1": "213",
            "-y2": "213"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.8",
            "-x2": "177.8",
            "-y1": "250.3",
            "-y2": "143.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "177.8",
            "-x2": "208.5",
            "-y1": "143.5",
            "-y2": "143.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.5",
            "-x2": "208.5",
            "-y1": "143.5",
            "-y2": "120.2"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.5",
            "-x2": "285.3",
            "-y1": "120.2",
            "-y2": "120.2"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.5",
            "-x2": "290",
            "-y1": "143.5",
            "-y2": "143.5"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.5",
            "-x2": "208.5",
            "-y1": "143.5",
            "-y2": "167.7"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "208.5",
            "-x2": "285.3",
            "-y1": "167.7",
            "-y2": "167.7"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "290",
            "-x2": "290",
            "-y1": "143.5",
            "-y2": "158.6"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "290",
            "-x2": "370.3",
            "-y1": "158.6",
            "-y2": "158.6"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "290",
            "-x2": "290",
            "-y1": "143.5",
            "-y2": "126.2"
          },
          {
            "-fill": "none",
            "-stroke": "#FF0000",
            "-stroke-linecap": "round",
            "-stroke-linejoin": "round",
            "-stroke-miterlimit": "10",
            "-stroke-width": "2",
            "-x1": "290",
            "-x2": "444",
            "-y1": "126.2",
            "-y2": "126.2"
          }
        ]
      }
    }
  }
}